CREATE TABLE IF NOT EXISTS history (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    market_ID INT NOT NULL REFERENCES market (ID),
	product_ID INT NOT NULL REFERENCES product (ID),
	quantity_ID INT NOT NULL REFERENCES quantity (ID),
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;
