CREATE TABLE IF NOT EXISTS history (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    market_ID INT NOT NULL,
	product_ID INT NOT NULL,
	quantity_ID BIGINT NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (market_ID) REFERENCES market(ID),
	FOREIGN KEY (product_ID) REFERENCES product(ID),
	FOREIGN KEY (quantity_ID) REFERENCES quantity(ID)
)  ENGINE=INNODB;
